name: Build and Push Backend Image

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'IzvorniKod/eSkolskaKomunikacija/**'      # Trigger only on changes in the backend directory
  workflow_dispatch:

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    env:
      BACKEND_DEPLOY_HOOK: ${{ secrets.BACKEND_DEPLOY_HOOK }}
      GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
          cache-dependency-path: 'IzvorniKod/eSkolskaKomunikacija/pom.xml'

      - name: Maven build
        run: |
          mvn clean package \
            -DGOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} \
            -DGOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        working-directory: IzvorniKod/eSkolskaKomunikacija

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./IzvorniKod/eSkolskaKomunikacija
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/u_zadnji_tren/backend:latest
          build-args: |
            GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
            GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

      - name: Trigger release
        if: ${{ env.BACKEND_DEPLOY_HOOK }}
        run: curl ${{ env.BACKEND_DEPLOY_HOOK }}
