name: Build and Push Frontend Image

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'IzvorniKod/eSkolskaKomunikacija/App/frontend/**'  # Trigger only on changes in the frontend directory
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    env:
      FRONTEND_DEPLOY_HOOK: ${{ secrets.FRONTEND_DEPLOY_HOOK }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'IzvorniKod/eSkolskaKomunikacija/App/frontend/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: IzvorniKod/eSkolskaKomunikacija/App/frontend

      - name: Build frontend
        run: npm run build
        working-directory: IzvorniKod/eSkolskaKomunikacija/App/frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Force lowercase repository owner
        run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./IzvorniKod/eSkolskaKomunikacija/App/frontend
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/u_zadnji_tren/frontend:latest

      - name: Trigger release
        if: ${{ env.FRONTEND_DEPLOY_HOOK }}
        run: curl ${{ env.FRONTEND_DEPLOY_HOOK }}
